Repository schmelto/LinkFree_generator, pull requests merged in 2022-06, with the labels that each got.

#1 fix: update ui and clear deadcode
  README.md
  index.html
  js/scripts.js
Labels: size/L

#3 Create LICENSE
  LICENSE
Labels: size/S

#7 feat: add issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: size/M

#19 fix(bug): links fields broken
  index.html
Labels: size/S

#20 feat: add icons from dropdown
  index.html
Labels: size/M

#26 Fixed Typo
  index.html
Labels: size/XS

#22 fix(bug): adding main element
  index.html
Labels: size/XS

#23 fix(bug): add missing aria-label on milestones section
  index.html
Labels: size/XS

#30 Button size inconsistency fixed
  index.html
Labels: size/XS

#31 Fix Heading Bug Reported
  index.html
  js/scripts.js
  package.json
Labels: size/S
